---
name: "build-modules"

concurrency: build

on:
  repository_dispatch:
    types: [build-modules]
  workflow_dispatch:
    inputs:
      modules:
        description: 'A comma-separated list of modules to be rebuilt'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.modules != '' || github.event.client_payload.modules != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: nhatthm/govanityrender-action@dev
        with:
          modules: ${{ github.event.inputs.modules == '' && github.event.client_payload.modules || github.event.inputs.modules }}

      - name: Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
