---
name: "build"

concurrency: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: nhatthm/govanityrender-action@dev

      - name: Check
        run: |
          tree -L 5 build/

      - name: Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
